# Generated by Django 4.0.6 on 2022-07-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_priority_options_alter_projectcolor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modify_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'db_table': 'sections',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['priority'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', 'id'], 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'title')},
        ),
        migrations.AddField(
            model_name='task',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task.section'),
        ),
    ]
