# Generated by Django 4.0.6 on 2022-07-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_picture'),
        ('task', '0003_section_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user_profile', 'title')},
        ),
        migrations.RemoveField(
            model_name='task',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
