# Generated by Django 4.0.6 on 2022-07-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_profile_picture'),
        ('task', '0004_alter_task_unique_together_task_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.projectcolor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
