# Generated by Django 4.0.6 on 2022-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='day_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
