# Generated by Django 4.0.6 on 2022-07-24 15:24

from django.db import migrations, models
import to_do_app.commons.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='static/image/profile', validators=[to_do_app.commons.validators.file_max_size_in_mb_validator]),
        ),
    ]
